pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3030:3030'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Sudah selesai menggunakan React App? (Klik "Proceed" untuk mengakhiri)'
                sh './jenkins/scripts/kill.sh'
            }
            post {
                success {
                    echo 'Application deployed successfully. Please wait for a minute...'
                    sleep time: 60, unit: 'SECONDS'
                }
            }
        }
        stage('Manual Approval') {
            steps {
                script {
                    def userInput = input message: 'Lanjutkan ke tahap Deploy?', parameters: [booleanParam(defaultValue: true, description: 'Pilih true untuk melanjutkan atau false untuk menghentikan', name: 'Proceed')]
                    if (userInput == true) {
                        echo 'Melanjutkan ke tahap Deploy...'
                    } else {
                        error 'Pipeline dihentikan oleh pengguna.'
                    }
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
